### ISSUE TITLE
Setup a static auto-generated website

### ISSUE THREAD

**Issue by NirantK** [keon/awesome-nlp#101]
We can set up a website at something like www.keon.github.io/awesome-nlp

**Reference Demo**: www.nirantk.github.io/awesome-project-ideas
which auto-updates from the Github repository at https://github.com/NirantK/awesome-project-ideas

The website would automatically pick up content and get up updated from the Markdown on our master/README.md. 

This should make it easier for search engines to rank and find us. It would also make it easier for some people e.g. academics, beginners like college students etc. 

@keon thoughts?

**Comment by aditya-giri** [comment]
@NirantK did you take down the website? Can't reach it.

**Comment by NirantK** [comment]
This repo never had a static website. What are you looking for?

**Comment by aditya-giri** [comment]
The one you linked in your comment. [This one](http://www.nirantk.github.io/awesome-project-ideas)

**Comment by NirantK** [comment]
Check https://nirantk.com

**Comment by NirantK** [comment]
This is the specific URL for awesome-project-ideas: https://nirantk.com/awesome-project-ideas/

Closing this issue for now, since we don't intend to make a static website for awesome-nlp
