### ISSUE TITLE
Add CNN for text classification in TensorFlow

### ISSUE THREAD

**Issue by the-ethan-hunt** [keon/awesome-nlp#104]
This is a blogpost and code from DennyBritz's [project](https://github.com/dennybritz/cnn-text-classification-tf). Should I add it?

**Comment by NirantK** [comment]
We don't have a right section for this kind of work. Maybe create a new *Text Classification* section and add there along with more relevant work?

**Comment by NirantK** [comment]
Few ideas to lookup around text classification: 
1. VD-CNN work
2. fastText Supervised work
3. RNN/LSTM work for text classification, like [this one](https://pdfs.semanticscholar.org/93eb/7d6592290e0b0fa6ee1cde7cb08d2f4aceb6.pdf)- but please look for something better as well? 
- Include some tutorials on this please if possible? 

Any other crazy ideas such as [Zero Short Learning for Text Classification](https://arxiv.org/abs/1712.05972) are also welcome if from peer-reviewed Tier 1 venues

**Comment by the-ethan-hunt** [comment]
@NirantK , I would like to work on this but I will be traveling and might not be quick in the PR.

**Comment by NirantK** [comment]
Sure, @the-ethan-hunt take your time. I will be working on #96 when I have some time.

**Comment by NirantK** [comment]
Hello @the-ethan-hunt, please close this issue if you think you have added all that you wanted to add. And thanks for the PR!

**Comment by the-ethan-hunt** [comment]
Alright! :smile:
