### ISSUE TITLE
Broken RNNLM toolkit link

### ISSUE THREAD

**Issue by the-ethan-hunt** [keon/awesome-nlp#105]
>A Neural Network Approach to Context-Sensitive Generation of Conversational Responses Sordoni 2015. Generates responses to tweets. Uses Recurrent Neural Network Language Model (RLM) architecture of (Mikolov et al., 2010). source code: RNNLM Toolkit

The toolkit source code link is broken

**Comment by NirantK** [comment]
Fixed in 41a9568 . Thanks for catching this @the-ethan-hunt !
