### ISSUE TITLE
Add @the-ethan-hunt as collaborator?

### ISSUE THREAD

**Issue by NirantK** [keon/awesome-nlp#112]
Hello @keon, 

Just wanted to check if we could add @the-ethan-hunt as a collaborator? 

It will allow faster contributions. 

He has made ample contributions imho, refer [author contributions](https://github.com/keon/awesome-nlp/commits?author=the-ethan-hunt)

**Comment by the-ethan-hunt** [comment]
@NirantK , I am already a contributor. ( Please see my comments on various issues; I have a contributor tag) 😅 . Maybe you meant a collaborator?

**Comment by the-ethan-hunt** [comment]
@NirantK , I am already a contributor. ( Please see my comments on various issues; I have a contributor tag) 😅 . Maybe you meant a collaborator?

**Comment by the-ethan-hunt** [comment]
Pinging @keon for this. :sweat_smile:

**Comment by keon** [comment]
Sorry for the delay :(
@the-ethan-hunt has been contributing a lot lately.
Thanks, and I invited you as the collaborator.

**Comment by NirantK** [comment]
Welcome @the-ethan-hunt !

**Comment by the-ethan-hunt** [comment]
Thank you for the warm welcome @NirantK ! Looking to contribute more to awesome-nlp :tada:
