### ISSUE TITLE
Add more languages corpora, tools and research

### ISSUE THREAD

**Issue by NirantK** [keon/awesome-nlp#113]
Indic
- [x] Hindi - To be done later
- [ ] Gujarati - To be done later
- [ ] Tamil
- [ ] Telegu
- [ ] Bengali

Asian
- [ ] Chinese
- [ ] Korean
- [ ] Japanese

We should be able to add content regarding Indian/Indic languages as well, keeping in mind the growth of India Stack and need for Indic tools.

**Comment by NirantK** [comment]
I will be working on this issue for a brief duration. 

I'd love to assist you @the-ethan-hunt if you are up to take the lead on this.

**Comment by the-ethan-hunt** [comment]
@NirantK , I would be happy to be assisted by you! But the pond is too large and the fish too small. :sweat_smile:

**Comment by NirantK** [comment]
Let's start small, let's get Hindi rolling with some work on datasets and
pre trained models. What do you think?

**Comment by the-ethan-hunt** [comment]
You are right!

**Comment by the-ethan-hunt** [comment]
@NirantK , a simple GitHub search is leading nowhere. Any leads to start this? :sweat_smile:

**Comment by NirantK** [comment]
Go old school. Search Google scholar for work by keywords like Hindi
language parsing, modeling etc.

Skip everything which says translation. That's often lazy work.

**Comment by the-ethan-hunt** [comment]
@NirantK , I went old school and discovered two good papers worth to be mentioned in this list:
- A POS tagger and chunker system for Hindi language using Maximum Entropy Markov Model. [Here](https://www.researchgate.net/profile/Uma_Sawant/publication/241211496_Hindi_Part-of-Speech_Tagging_and_Chunking_A_Maximum_Entropy_Approach/links/571255cb08aeff315ba0d302.pdf) is the paper
- A lightweight stemmer for Hindi [link](http://kbcs.in/downloads/papers/StmmerHindi.pdf)
IMHO, there has been negligible research conducted for NLP in Tamil, Telugu, Marathi and other Indian languages

**Comment by NirantK** [comment]
Welcome @arpita.batra to the thread. She did her thesis on Hindi Text Processing. Some of the cool stuff she mentioned: 

- English Hindi Parallel Corpus http://www.cfilt.iitb.ac.in/iitb_parallel/ 
- Hindi Wordnet http://www.cfilt.iitb.ac.in/wordnet/webhwn/ 
- Sanskrit Mini Corpora from JNU: http://sanskrit.jnu.ac.in/corpora/tagset.jsp
- Indo Wordnet, no download option, but supports Gujarati and other Indic languages  http://www.cfilt.iitb.ac.in/indowordnet/index.jsp

**Comment by the-ethan-hunt** [comment]
@NirantK , sure!
Thanks for the stuff Arpita! And welcome to `awesome-nlp`! :smile:

**Comment by arpitabatra** [comment]
POS tagging related papers. 
- Morphological Richness Offsets Resource Demand- Experiences in Constructing a POS Tagger for Hindi
[link](https://dl.acm.org/citation.cfm?id=1273173)
- Building Feature Rich POS Tagger for Morphologically Rich Languages: Experiences in Hindi
[link](https://www.researchgate.net/profile/Uma_Sawant/publication/250797503_Building_Feature_Rich_POS_Tagger_for_Morphologically_Rich_Languages_Experiences_in_Hindi/links/5712559008aeff315ba0d2fc.pdf)
- Hindi POS Tagger Using Naive Stemming : Harnessing Morphological Information Without Extensive Linguistic Knowledge
[link](https://www.cse.iitb.ac.in/~pb/papers/icon08-hindi-pos-tagger.pdf)

**Comment by NirantK** [comment]
Sure @arpitabatra, that's a good insight. We should definitely look into those. Please do help us around that. 

Sidenote: If there are any glaring holes in Hindi Text Processing, please mention them as well, they can become research avenues for people after us. We can note and detail those challenges in a separate repository/markdown file as well. 

@the-ethan-hunt, I think we both can focus on Gujarati/other Indic languages as @arpitabatra has been kind enough to share her expertise with us on Hindi. What do you think?

**Comment by the-ethan-hunt** [comment]
@NirantK , yes I agree with you. And while tinkering around, I found [this](http://universaldependencies.org/). There are huge treebanks of several languages(both Indian and foreign).
Should I make a PR for this?

**Comment by NirantK** [comment]
Hey @the-ethan-hunt That's a good find. Let's link to [Hindi specific work](http://universaldependencies.org/treebanks/hi-comparison.html) for now. 

May be we need to look into more tooling, datasets and academic work beyond treebanks, POS taggers and actually compile the best from what is out there? 

If I was starting looking into Hindi NLP, the above list of work is not even 20-30% of what I'd need to get started.

**Comment by the-ethan-hunt** [comment]
@NirantK , there is also [this](http://ltrc.iiit.ac.in/treebank_H2014/) treebank prepared by several American universities. The thing here is, that both the mentioned treebanks are annotated ones; this would largely help linguistics experts and NLP scientists to stop using their time annotating their corpora.

**Comment by NirantK** [comment]
That is already in the list from @arpitabatra :)

**Comment by the-ethan-hunt** [comment]
@NirantK , any points we can start working? Like the Universal Dependencies thing? :smile:

**Comment by NirantK** [comment]
@the-ethan-hunt 
Why we need data to work in NLP? 

- Dictionaries and WordNets are useful for syntactic tasks
- Large text corpus is useful for lot of tasks such as text classification, text embeddings, and so on

Then, in terms of data, we need the following: 

- [ ] Dictionaries e.g. Gujarati to English and vice versa
- [ ] Large News corpus similar to CNN or DailyMail ones 

I hope that this helps us streamline our efforts. I will look into large news corpus, if unavailable at least list them down a few major websites which we can use to generate that dataset.

**Comment by NirantK** [comment]
Hey @arpitabatra @the-ethan-hunt, please go ahead and raise one PR for Hindi datasets (excluding the work on POS, Stemming etc) as soon as you have sometime? 

The work isn't quite sufficient to get started in terms of tools, but I think we should share the datasets atleast as we've done for Spanish.

**Comment by the-ethan-hunt** [comment]
@NirantK , regarding the shift of the language section to NLP-Progress as discussed in this [thread](https://github.com/sebastianruder/NLP-progress/issues/79), should I raise PRs for new resources here or at NLP-Progress?
Does it sound alright, @sebastianruder ? :sweat_smile:

**Comment by NirantK** [comment]
@the-ethan-hunt 

If there are performance numbers available, or high user trust in that lib - raise it directly at NLP-Progress. 
If not, raise them there here for now. 

There is a lot of work which does not have results. E.g. datasets, Python libs in Arabic/Hindi etc. 
They are *good enough* for programmers quite often. We can discuss and sort those edge cases out.

**Comment by sebastianruder** [comment]
Just to be clear: `awesome-nlp` should stay awesome, so we shouldn't remove anything from here from now and `awesome-nlp` should still be the place where libraries and tools, etc. are collected.
As @NirantK mentions, anything with reported results and standard evaluation setups can be added to `nlpprogress`.

**Comment by Shashi456** [comment]
@NirantK i think this library can be added as tool for indic languages 
http://anoopkunchukuttan.github.io/indic_nlp_library/

**Comment by NirantK** [comment]
Thanks for the hunt!

That was not included here because

- The core lib has not been updated in 4+ years, is still Py2.7 for some
reason
- Is not Unicode compliant for some reason?

I had some trouble installing it as well on Linux and Windows. In other
words, this is not awesome.

**Comment by Shashi456** [comment]
also @NirantK I think [ACL 2018 highlights](http://ruder.io/acl-2018-highlights/) by Sebastian ruder should be added to the research trends and summaries

**Comment by NirantK** [comment]
@Shashi456 please raise a MR for Ruder's highlights with a 1 line explanation and we'll review the same?

**Comment by Shashi456** [comment]
@NirantK do you know of any Indic libraries other than that, i've been scourging the internet for some but have found none satisfiable

**Comment by NirantK** [comment]
One, I recall seeing few more like the one you mentioned above. The
recurring challenge being that almost none of them are Unicode compliant
and poorly maintained. 2 of them did not have a setup.py for installation.

Two, I have mostly worked with Hindi (e.g.
https://github.com/NirantK/hindi2vec/ )  - simple tokenization is solved
with 'space' splits and simple rules around word suffixes.

Three, spaCy (https://github.com/explosion/spaCy) works for me in most
cases.
Please consider contributing to the same if you want to build a NLP toolkit
for Indic scripts.

**Comment by guillaume-chevalier** [comment]
Hello @NirantK, I made this project for clustering/topic extraction: https://github.com/ArtificiAI/Multilingual-Latent-Dirichlet-Allocation-LDA

It also contains a tutorial explaining the architecture: https://github.com/ArtificiAI/Multilingual-Latent-Dirichlet-Allocation-LDA/blob/master/Stemming-words-from-multiple-languages.ipynb

It also has unit tests. 

All those languages are supported:
- Danish
- Dutch
- English
- Finnish
- French
- German
- Hungarian
- Italian
- Norwegian
- Porter
- Portuguese
- Romanian
- Russian
- Spanish
- Swedish
- Turkish

I was hesitating whether or not to add a new section, such as "Many languages". My question is: what would you do? Where would you add this?

Thank you!

**Comment by NirantK** [comment]
@guillaume-chevalier that should go under Libraries -> Python. Please raise a PR. Great to see a multi-lingual clustering toolkit!

**Comment by NeroCube** [comment]
Hi @NirantK, I can support Traditional Chinese translation and I am currently working on [it](https://github.com/NeroCube/awesome-nlp/blob/master/README-zh-TW.md).
This is really awesome repo, hope more people can see.

**Comment by NirantK** [comment]
Wow, this is fantastic @NeroCube! Can you please raise a PR with your translation?

**Comment by goru001** [comment]
@NirantK Do you think adding links to repos [NLP for Hindi](https://github.com/goru001/nlp-for-hindi), [NLP for Punjabi](https://github.com/goru001/nlp-for-punjabi) , [NLP for Sanskrit](https://github.com/goru001/nlp-for-sanskrit), [NLP for Gujarati](https://github.com/goru001/nlp-for-gujarati), [NLP for Kannada](https://github.com/goru001/nlp-for-kannada), [NLP for Malayalam](https://github.com/goru001/nlp-for-malyalam), [NLP for Nepali](https://github.com/goru001/nlp-for-nepali), [NLP for Odia](https://github.com/goru001/nlp-for-odia), [NLP for Marathi](https://github.com/goru001/nlp-for-marathi), [NLP for Bengali](https://github.com/goru001/nlp-for-bengali), [NLP for Tamil](https://github.com/goru001/nlp-for-tamil), [NLP for Urdu](https://github.com/anuragshas/nlp-for-urdu) under the Indic Languages section would be helpful? All these repos contain Language Models, Classifiers and Tokenizers for their respective languages and are being used in [iNLTK](https://github.com/goru001/inltk)

**Comment by NirantK** [comment]
We already have iNLTK, which in turn links to all of the above. 

Maybe not add all of them? This might get spammy.

**Comment by goru001** [comment]
Yes okay! That seems right! Thanks!

**Comment by NirantK** [comment]
Thank you everyone who has contributed to the multiple languages work, here on Awesome-NLP. While we continue to welcome the contributions along similar lines, we have some sort of coverage now. 

I'm closing this issue for now. We will open new issues to encourage specific discussions.
