### ISSUE TITLE
Add Gujarati Resources

### ISSUE THREAD

**Issue by NirantK** [keon/awesome-nlp#114]
Here is the academic work I could find: 

1. [Clustering Algorithm for Gujarati words, 2012](https://arxiv.org/ftp/arxiv/papers/1307/1307.5393.pdf)
2. [Gujarati-Hindi Machine Translation, 2013](https://arxiv.org/ftp/arxiv/papers/1307/1307.3310.pdf)
3. [Lightweight Stemmer for Gujarati, 2013](https://arxiv.org/ftp/arxiv/papers/1210/1210.5486.pdf)

None of the above work is inspiring but this is what we have.

**Comment by NirantK** [comment]
List of Newspapers: 
http://www.gujaratilexicon.com/newspapers/

Had no luck finding ready-made text corpus. Might consider making one soon.

**Comment by the-ethan-hunt** [comment]
@NirantK , since awesome-nlp is a curated list of the best resources, is it absolutely necessary to include these? Just a question. :sweat_smile:

**Comment by NirantK** [comment]
It is not. We can choose to decide that this is not up to the mark. 

But to make that decision, we at least had to take a look, so I went and did that.

**Comment by NirantK** [comment]
Choosing not to add above resources as they are not of sufficient quality. Marking the issue as closed, though contributions are welcome :) 

Cc: @the-ethan-hunt
