### ISSUE TITLE
Channel for chat

### ISSUE THREAD

**Issue by the-ethan-hunt** [keon/awesome-nlp#116]
I would like to propose a channel like Slack or Gitter for chat for the following reasons:
- Issue discussion can be done more easily
- Enhancement suggestions can be discussed more openly

Would like to hear about it from other maintainers- @keon, @outpark   and @NirantK

**Comment by NirantK** [comment]
+1 to the idea

I am open to Gitter, but it's tough to keep track of the discussion there
as well.

Maybe avoid Slack as it gets Spammy really quickly?

**Comment by the-ethan-hunt** [comment]
The reason I would like a communication channel is instead of commenting on the issues themselves, they can be more openly discussed on Gitter. Cool with Gitter, BTW

**Comment by NirantK** [comment]
Hello, 

Gitter with the handle awesome-nlp is [live on this link](https://gitter.im/awesome-nlp/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link)

 @the-ethan-hunt: Over to you from here. Please close this issue whenever possible :)

**Comment by the-ethan-hunt** [comment]
Closing this issue. :)
