### ISSUE TITLE
Add Contribution Guidlines

### ISSUE THREAD

**Issue by keon** [keon/awesome-nlp#13]

**Comment by vs1682** [comment]
Just copied it from different awesome repos.
Check if you want to add anything else.
We can add that every code related addition should be above blogs and credits

# Contribution Guidelines

Please ensure your pull request adheres to the following guidelines:

- Search previous suggestions before making a new one, as yours may be a duplicate.
- Make an individual pull request for each suggestion.
- Use the following format: `[Bookmark Title](link): Description.`
    - The title usually consists of several words. For bookmarks of an article or tutorial, use the title of the article.
    - The description consists of one-two sentences about the bookmark. It is required.
- If the resource has 2 or more links please provide the Github repo link.
- Additions should be added to the bottom of the relevant category.
- New categories or improvements to the existing categorization are welcome.
- Check your spelling and grammar.
- Make sure your text editor is set to remove trailing whitespace.
- The pull request and commit should have a useful title.

Thank you for your suggestions!

**Comment by jsroyal** [comment]
@keon I would like to send PR. Also, @vs1682 already mention here very nice points. So taking his input and write in PR_TEMPLATE.md

**Comment by keon** [comment]
@jsroyal sounds good!

**Comment by jsroyal** [comment]
@keon I think this issue should be closed now.
Maybe if you want to update the content but prior level it has been done.

**Comment by jsroyal** [comment]
@keon Thanks!! Looking forward to more PR. :100:
