### ISSUE TITLE
Chazutsu is a Python library for reading standard text datasets

### ISSUE THREAD

**Issue by LanceNorskog** [keon/awesome-nlp#137]
I haven't tried it.

https://github.com/chakki-works/chazutsu

**Comment by NirantK** [comment]
Hey, this looks good. Thanks for sharing @LanceNorskog. 

I will try this myself and will include it here if it's good. Thanks!

**Comment by NirantK** [comment]
Hey @LanceNorskog, I think we will go ahead and include this. Since this is your find, I'd request you to raise a Pull Request. You can do that in-browser itself. 

Closing this issue - look forward to seeing your PR :)
