### ISSUE TITLE
Reproduce Hierarchical Attention Networks for Document Classification for German

### ISSUE THREAD

**Issue by the-ethan-hunt** [keon/awesome-nlp#160]
[German NLP](https://github.com/adbar/German-NLP) is a curated list of German NLP resources including datasets.

P.S. This paper is one of the first to work on Embed, encode, attend, predict.

**Comment by NirantK** [comment]
Hey @the-ethan-hunt are these new issues for the Recipe work we are doing with KWOC? 
If yes, we should also label NLP Recipes or something similar.

**Comment by the-ethan-hunt** [comment]
Yes, @NirantK . I will add the `Recipes` tag. My bad forgot it.

**Comment by NirantK** [comment]
@the-ethan-hunt is there anyone going to be working on the Recipe related projects? If not, let's close these out and reduce some clutter.

**Comment by NirantK** [comment]
.@the-ethan-hunt closing these `recipe` issues for now.
