### ISSUE TITLE
Traditional Chinese(zh-TW) language support 

### ISSUE THREAD

**Issue by NeroCube** [keon/awesome-nlp#172]
Hi @keon  ,This is an awesome project.I hope more people can see .
I have completed the translation of Traditional Chinese and I have made a [PR](https://github.com/keon/awesome-nlp/pull/171).
May you add the Traditional Chinese version on this repo?

**Comment by NirantK** [comment]
Done. Your PR is merged @NeroCube. 

Thanks a ton for this amazing effort. I'm sure this will benefit thousands of Chinese readers! 

Please do share this on Chinese social media!

**Comment by NeroCube** [comment]
Thanks! I will do my best to let more Chinese users see this awesome project.
