### ISSUE TITLE
Add Research Labs

### ISSUE THREAD

**Issue by the-ethan-hunt** [keon/awesome-nlp#174]
Considering the recent surge in NLP research, I propose the listing of some of the top labs that are carrying cutting-edge research in NLP (no endorsements, here) like Stanford NLP group, University of Edinburgh NLP group etc.

@NirantK how does this sound?

**Comment by NirantK** [comment]
Sounds good. Raise a pull request? Mention their recent work/ticket to fame
as well?

**Comment by NirantK** [comment]
Merged #176
