### ISSUE TITLE
Any support for Gujarati

### ISSUE THREAD

**Issue by dvatsal** [keon/awesome-nlp#206]
Any support for Gujarati? I think you are from Surat hence thought some support might be there for Gujarati as well

**Comment by NirantK** [comment]
What are you looking for exactly? 

We already list
- StanfordNLP
- iNLTK ->https://github.com/goru001/nlp-for-gujarati

Both of these cover the most cases for Gujarati in addition to LASER and fasttext. 

I don't see any explicit work in Gujarati, like translation.

**Comment by dvatsal** [comment]
I am looking for something like word2vec, etc if you are aware of any

**Comment by mapmeld** [comment]
@dvatsal There are Gujarati word embeddings in [FastText](https://fasttext.cc/docs/en/pretrained-vectors.html) and in [Multilingual BERT](https://github.com/google-research/bert/blob/master/multilingual.md)

**Comment by dvatsal** [comment]
Thanks @mapmeld

**Comment by NirantK** [comment]
Thanks @mapmeld! 

Closing the issue @dvatsal since this seems to be resolved for now
