### ISSUE TITLE
Which kind of model is better for keyword-set classification?

### ISSUE THREAD

**Issue by guotong1988** [keon/awesome-nlp#213]
There exists a similar task that is named text classification.

But I want to find a kind of model that the inputs are keyword set. And the keyword set is not from a sentence.

Thank you.

**Comment by NirantK** [comment]
Can you give an example of this kind of problem? 

What do you mean by keyword? And why can you not do a direct lookup in your target corpus?

**Comment by guotong1988** [comment]
1,
input ["apple", "pear", "water melon"] --> target class "fruit"
input ["tomato", "potato"] --> target class "vegetable"

2,
I want find the better model.

**Comment by NirantK** [comment]
You need a WordNet ontology. This is not a text classification problem. 

I am not sure if this is the right forum to ask for help around this.
