### ISSUE TITLE
Update the link of Natural Language Processing  professor Mike Collins

### ISSUE THREAD

**Issue by jsroyal** [keon/awesome-nlp#50]
As you mention here the video are not available and I go through the link it's not there so it would be better to update with this [link](http://www.cs.columbia.edu/~mcollins/)

**Comment by NirantK** [comment]
Hey @jsroyal, sorry for the delay in updating the link. We have added the video links in a recent commit here: 171816212094a5155b79a2f731228572df082b5a 

@keon, maybe we can close this issue?

**Comment by keon** [comment]
@NirantK sure thanks
