### ISSUE TITLE
fasttext

### ISSUE THREAD

**Issue by fshabashev** [keon/awesome-nlp#51]
I think one should add "fasttext" to list. 
It is new library developed by FAIR team together with Thomas Mikolov.
It can do everything word2vec can, but faster. It also provides more features: model compression, supervised classification, character n-grams.

**Comment by NirantK** [comment]
@keon maybe this can be closed with reference to the commit 853f978deb48704b3f58dbd223357de012b2a40e ?

**Comment by keon** [comment]
yes sir!
