### ISSUE TITLE
Add new maintainers?

### ISSUE THREAD

**Issue by keon** [keon/awesome-nlp#80]
I think it is a good idea to add more maintainers so we can keep up to date.
We are also going to polish the list. Please let me know if anyone is interested.

@NirantK - Are you interested?

**Comment by NirantK** [comment]
Sure, I'd love to help. 

Before we move ahead, I am new to FOSS.  What is a good maintainer supposed to do?

**Comment by keon** [comment]
nothing special, you just get a right to merge PR or directly commit to the repo.

**Comment by the-ethan-hunt** [comment]
@keon,I would love to be a maintainer :smiley:

**Comment by keon** [comment]
@the-ethan-hunt 
I think the maintainers should have certain amount of contribution beforehand.
closing the issue since @NirantK accepted the invitation.

**Comment by NirantK** [comment]
Thanks for the invite @keon!

Hey @the-ethan-hunt, why not help us close a few issues and we'd take it from there? We've marked some [beginner friendly issues here](https://github.com/keon/awesome-nlp/labels/good%20first%20issue). 

You can get started from within your browser now. Just select any issue, let us know that you are taking it up by working on it and raise a pull request when you are done!

**Comment by the-ethan-hunt** [comment]
Sure! Thanks for helping out @NirantK !
