### ISSUE TITLE
Add awesome-nlp to awesome.re? 

### ISSUE THREAD

**Issue by NirantK** [keon/awesome-nlp#84]
[Awesome.re](https://github.com/sindresorhus/awesome) is a meta-list of awesome repositories. 

It has a few [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) to be included there. 
Maybe we can use that as our checklist to improve this. And then raise a PR when we are done? 

What do you suggest @keon ?

**Comment by keon** [comment]
sounds good!

also, for long term...
I wanted to work on a script that allows us to store the lists in some sort of json or list that could automatically be used for parsing, verifying the url, and generating the README.md.

**Comment by NirantK** [comment]
The script sounds like a good idea: 
- make our jobs easier as maintainers
- does it make it more difficult to contribute to README.md then write now? 

Keeping in mind that most contributors are contributing directly from their browsers. Maybe we should add that script to a Pull Request hook? Include formatting checks in the script itself - similar to Bandit for code?

**Comment by NirantK** [comment]
@keon just following up, do you have any more inputs on what we want from the `json2md` (json to markdown) script?

**Comment by NirantK** [comment]
@the-ethan-hunt would you like to take lead on this and guide us on what we need to get done to add awesome-nlp to awesome.re?

**Comment by the-ethan-hunt** [comment]
@NirantK , I find that awesome-nlp has all the required stuff to be included in the awesome.re list. Should we pull a request? Or maybe @keon should(He is the original maintainer of the project :smile: )?

**Comment by NirantK** [comment]
Let's not wait for @keon. Please raise a PR there. Please double check that we are visible in a separate section. 

Preferably not absorbed under wider and less maintained Speech and Natural Language Processing sections ;) 

I'd like for people to find us as easily as possible.

**Comment by the-ethan-hunt** [comment]
>Includes a project logo/illustration whenever possible.

We might be lagging here. any suggestions on how to proceed on this? :sweat_smile:

**Comment by NirantK** [comment]
Hmm, I had looked at a few examples back in January. We'll probably start with a cover image as in #94 and then just ask the awesome.re maintainer for advice. 

Adding section specific images would ruin the repo organization and make it longer than it already is.

**Comment by the-ethan-hunt** [comment]
How about pulling a request **here** about the cover image ideas you had and then we can decide the appropriate image?

**Comment by NirantK** [comment]
Good idea, I will raise a PR for it. 

Since this is going to take some time from my end. Anything else other than that we need doing?

**Comment by the-ethan-hunt** [comment]
Nope,not at all
Secondly, @keon raised this issue [here](https://github.com/sindresorhus/awesome/issues/677)
The maintainer has asked about the status of our list(a year ago). Is it wise to reply back now with an apology? :smile:

**Comment by NirantK** [comment]
Thanks for bringing that to notice. I somehow missed that completely. 

Sure, please go ahead and tell @sindresorhus that we are helping keon maintain this. 

And we would like to include the list as we've updated (and expanded) it significantly over last 4-6 months.

**Comment by the-ethan-hunt** [comment]
Done! All we need to do is wait for his comment while we plan out a cover image.

**Comment by NirantK** [comment]
Sounds good. Thanks!

**Comment by NirantK** [comment]
@the-ethan-hunt please follow up?

**Comment by the-ethan-hunt** [comment]
@NirantK , @keon created a new issue here, [see](https://github.com/sindresorhus/awesome/issues/1236). We are still waiting for a response from the maintainers of the `awesome.re` project

**Comment by the-ethan-hunt** [comment]
@NirantK , there has been no fresh leads on the issue. Any ideas to proceed further?

**Comment by NirantK** [comment]
No, have stopped pursuing this. There has been no response on the old and new issues by the repo maintainer there. 

We can try to raise a clean PR to that repo as per the [new issue](https://github.com/sindresorhus/awesome/issues/1236) and see if that get's accepted. 

Else, close this issue please

**Comment by the-ethan-hunt** [comment]
Sure. But before submitting another PR, we should maybe have a cover image first. Closing this issue nonetheless.
