### ISSUE TITLE
Add license to the repository?

### ISSUE THREAD

**Issue by NirantK** [keon/awesome-nlp#86]
Do you think we should add a [MIT](https://tldrlegal.com/license/mit-license) or [CC0](https://tldrlegal.com/license/creative-commons-cc0-1.0-universal) license to the repository? 

This would 
- make it explicit that we (the maintainers) are not liable 
- allow developers working for corporations to use the listing here more freely
(not specifying a license makes [corporate legal itchy](https://choosealicense.com/no-permission/))

awesome meta-list [recommends CC0](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) probably because it is more permissive than MIT, AGPL and the like. 

What do you suggest?

**Comment by NirantK** [comment]
Hello @keon, just following up to hear from you on this. 
You can assign to me if you think we should add CC0, and I'll do it.

**Comment by keon** [comment]
Sorry for the late reply.
Ive taken a look at the LICENSE templates, but github only seems to support MIT.
It'd be nice if you could add CC0

**Comment by NirantK** [comment]
Added License in 5cb5c1e308b0645abc5c2e6388c460822527579b
