### ISSUE TITLE
Add new Machine Translation content

### ISSUE THREAD

**Issue by NirantK** [keon/awesome-nlp#89]
Machine Translation has explored CNNs, made encode-decoder architectures a norm and other changes since the last update. Please add *recent papers, demos, tutorials* and 1-2 line explanations for each link. 

If you know of better content, please add to this space.

**Comment by the-ethan-hunt** [comment]
I scoured over this and have found 2 such tutorials: One by Google research(in Python) and one by Prof. Graham Neubig(CMU) in Perl. Should I start by adding them?

**Comment by NirantK** [comment]
Sure. Add a brief description to the links as well please?

**Comment by NirantK** [comment]
Thanks for the PR @the-ethan-hunt (#90) Would you like to add a few recent papers, say which use CNN for Machine Translation? There's some work from Facebook AI Research team

**Comment by the-ethan-hunt** [comment]
@NirantK , sure! Let me do some more research and I will send a Pr in a couple of hours. :smile:

**Comment by NirantK** [comment]
Machine Translation section is revised and updated. Thanks to the efforts of @the-ethan-hunt !
