### ISSUE TITLE
Add banner image

### ISSUE THREAD

**Issue by NirantK** [keon/awesome-nlp#94]
We need to find and add a banner image similar to [awesome-qauntified-self](https://github.com/woop/awesome-quantified-self) or [awesome-electron](https://github.com/sindresorhus/awesome-electron)

This is towards the broader goal of making this list more polished. And raise a PR to awesome.re

Requests to anyone sending a PR: 
* Either fullwidth or placed at the top-right of the readme. [Example here](https://github.com/sindresorhus/awesome-electron)
* Image should link to the Github URL of the project
* Image should be high-DPI. Set it to maximum half the width of the original image.

**Comment by the-ethan-hunt** [comment]
@NirantK ,any leads on this?

**Comment by NirantK** [comment]
Sorry, not yet. I am quite occupied with other projects such as hindi2vec
at this moment.

**Comment by error404notfound** [comment]
Is there a particular image that you would like to use?

**Comment by NirantK** [comment]
@error404notfound No, we were fine with anything that meets the awesome.re guidelines.

**Comment by NirantK** [comment]
Title: Calm Community
![1-awesome-nlp](https://user-images.githubusercontent.com/3250749/46230592-af5de380-c386-11e8-8d73-86f38e5942e3.JPG)
---
Title: Minimalist Charm
![2-awesome-nlp](https://user-images.githubusercontent.com/3250749/46230593-aff67a00-c386-11e8-9a38-7544ab716017.JPG)
---
Title: Emptiness
![3-awesome-nlp](https://user-images.githubusercontent.com/3250749/46230594-aff67a00-c386-11e8-946c-5d9be5a183e6.png)
---
Title: Good Ol' Times
![4-awesome-nlp](https://user-images.githubusercontent.com/3250749/46230595-b08f1080-c386-11e8-8543-ecf5ceb1c1f8.png)
---

@keon @the-ethan-hunt suggestions for the logo/banner image! 

I like Calm Community the most, followed by Good Ol' Times. Let me know what you think **soon** please?

**Comment by NirantK** [comment]
Asking this on Twitter as well now: https://twitter.com/NirantK/status/1045766491143114752

**Comment by the-ethan-hunt** [comment]
The "calm community" one seems very attractive for our list

**Comment by NirantK** [comment]
Both Calm Community and Minimalist Charm were liked on the [Twitter poll](https://twitter.com/NirantK/status/1045766494641164288). 

Our new logo is live!

![Calm Community](https://user-images.githubusercontent.com/3250749/46434964-c596e580-c772-11e8-9d7d-036a40a3323e.JPG)

**Comment by keon** [comment]
Thanks @NirantK !
I love the new logo.

**Comment by NirantK** [comment]
Thanks @keon !
