### ISSUE TITLE
Add Github topics

### ISSUE THREAD

**Issue by NirantK** [keon/awesome-nlp#95]
Hello @keon, 

[Github topics](https://help.github.com/articles/about-topics) allow Github beginners to "discover" us. It also makes it possible for us to feature in the [Discover Dashboard](https://github.com/dashboard/discover). 

Since only **owners** can add Github topics, can you please add some topics? Here are a few suggestions: 
1. `awesome-list`
2. `awesome`
3. `natural-language-processing`
4. `text-mining`
5. `deep-learning` or `machine-learning`

Adding a quick screenshot to help you find where to add Github topics: 
![githubtopics](https://user-images.githubusercontent.com/3250749/34709375-fc9a37c0-f53c-11e7-93d5-4f8e40c21aea.png)

**Comment by keon** [comment]
Done! thanks for the suggestion.
Feel free to add more if you have more ideas.
