### ISSUE TITLE
Write a custom awesome-linter 

### ISSUE THREAD

**Issue by NirantK** [keon/awesome-nlp#97]
Standardize all links into some schematic/syntax. Here are few suggestions: 

- The link and description are separated by a dash. 
Example:  `[AVA](…) - JavaScript test runner`
- Section description starts with an uppercase character and ends with a period.
- Drop all the A / An prefixes in the descriptions. Don't begin sentences with `This`, `here` or `that`
- Consistent and correct naming. For example, Node.js, not NodeJS or node.js.
- Do not end bullet points of links with `.` or full stops, this makes it easier to read

We can then consider setting up a CI like Circle CI or Travis and run this linter on every PR automatically. 

---
This linter would be incredibly useful beyond `awesome-nlp` to several other `awesome-*` repositories. The value created from your effort must be seen in that context.

**Comment by NirantK** [comment]
I found [awesome-lint](https://github.com/sindresorhus/awesome-lint) from the creator of awesome.re for creating and maintaining awesome lists and roughly the same recommendations. 

Cc: @the-ethan-hunt want to help us setup Travis with this? Good excuse to pick up how CI configs work.

**Comment by the-ethan-hunt** [comment]
@NirantK , sure! But I am a little beginner in CI configs. How may I start?

**Comment by NirantK** [comment]
Since we are leaning towards Travis, start here:
https://docs.travis-ci.com/user/getting-started/
This is simple enough to understand.

The basic ideas are as follows:

   1. CI is basically a list of scripts which are run on certain triggers
   (such as pull request)
   2. The config file specifies what environment, scripts, setup etc and in
   what order do you want to setup. Config files are usually written in YML
   files. YML files are plain text files in a specific syntax. I like to think
   of them as Markdowns for Machine reading.

Here is a really simple travis config file for reference:
https://github.com/sindresorhus/awesome-lint/blob/master/.travis.yml

You can find details of what else to write for our lint:
https://github.com/sindresorhus/awesome-lint

---

As a risk-free way to get your hands dirty, I suggest setting up CI on your
fork of awesome-nlp first. They make a small edit in a different branch
from master.
Then, raise a merge request from your `newbranch` to `master`. This should
trigger a detailed Travis report.

Get to this point and expose the report to everyone on Github who can see
that PR to your master. At that point, simply mention the link to that PR
in the comments on this issue.
We will take it up from there. As always, let us know if you've any
questions!

**Comment by NirantK** [comment]
As a risk-free way to get your hands dirty, I suggest setting up CI on your
fork of awesome-nlp first. They make a small edit in a different branch
from master.
Then, raise a merge request from your `newbranch` to `master`. This should
trigger a detailed Travis report.

Get to this point and expose the report to everyone on Github who can see
that PR to your master. At that point, simply mention the link to that PR
in the comments on this issue.

We will take it up from there. As always, let us know if you've any
questions!

**Comment by the-ethan-hunt** [comment]
@NirantK , I tried but the CI seems to fail everytime. See [here](https://github.com/the-ethan-hunt/awesome-nlp/pull/2)

**Comment by NirantK** [comment]
​​
The issue seems to be syntactic and in the configuration file.

Please check this line:

The command "rvm use -2.2 --install --binary --fuzzy" failed and exited
with 1 during .

The command line option `rvm` does not recognise -2.2 as a flag. Maybe it's
supposed to be
Maybe it's supposed to be only `2.2` and not `-2.2`?

Also, refer https://github.com/travis-ci/travis-ci/issues/7077
It seems like this is not the recommended Ruby version.

Additionally, why Ruby? There is a pre-written awesome-lint
<https://github.com/sindresorhus/awesome-lint/> in NodeJS.

**Comment by the-ethan-hunt** [comment]
@NirantK , I did what you suggested and changed it to the awesome lint. There are still issues which I am not able to understand :sweat_smile: . See [here](https://github.com/the-ethan-hunt/awesome-nlp/pull/3)

**Comment by the-ethan-hunt** [comment]
@NirantK , I have done what you suggested and was stuck up again. See [here](https://github.com/the-ethan-hunt/awesome-nlp/pull/3). I have changed it to awesome lint

**Comment by NirantK** [comment]
I checked this
<https://travis-ci.org/the-ethan-hunt/awesome-nlp/builds/328173221?utm_source=github_status&utm_medium=notification>
and
this is ready to go! Good job!

This is the expected output from a CI tool. A CI tool runs a pre-determined
set of scripts (in our case the `awesome-lint`) against our code or README.
These scripts give us feedback on what we can do better, possible errors or
bad programming practices. For instance, at my workplace, we have an
automatic pipeline which forces each python function and class to have
a docstring (a comment) before it goes to a human for review. This is
automated using a CI tool running an internal script to check for that.

The CI is now printing specific errors which we need to fix. For instance I
can see a lot of:

Marker style should be - unordered-list-marker-style

These imply that there a lot of formatting fixes that we need to make to
comply with the awesome-lint.
That's great feedback. This becomes our checklist of issues to fix now.

Good stuff @the-ethan-hunt!

**Comment by the-ethan-hunt** [comment]
@NirantK Yes, I saw the same thing but I could not understand it :sweat_smile: . You explained me in a really good way

**Comment by NirantK** [comment]
Hey @the-ethan-hunt, can you please send a PR with the travis yml file (which is now tested at your own fork)?

**Comment by the-ethan-hunt** [comment]
@NirantK , is it fine if I send by tomorrow morning? :sweat_smile:

**Comment by NirantK** [comment]
Yeah, take your time. I just left a reminder as I really appreciate the
help :)

Thanks!

**Comment by the-ethan-hunt** [comment]
Shall we close this issue now? :sweat_smile:

**Comment by NirantK** [comment]
.@the-ethan-hunt we cannot close this just yet, because integration with Travis CI still remains. As @keon is the only owner, only s/he can configure it such that each PR triggers the CI run.

**Comment by keon** [comment]
@NirantK sure, I'll work on it today

**Comment by keon** [comment]
#128

**Comment by NirantK** [comment]
Thanks @keon @the-ethan-hunt for the good work. 
 
This should now help us follow a certain discipline and style in adding links. Closing this issue now as the linter is up and running now :)
