### ISSUE TITLE
Create Asian-language specific sections

### ISSUE THREAD

**Issue by NirantK** [keon/awesome-nlp#98]
To become the go-to resource, we should be able to curate good tools and datasets in at least the following languages (in addition to English): 

- [x] Chinese 
- [ ] Korean
- [ ] Japanese

Of course, we are willing to accept PRs from _all_ other languages. 

Please feel free to raise a PR or simply comment on this issue itself and we will add it on your behalf. 

@keon 

1. Thoughts? Is this a good direction to take? 

2. Can you take up any of the languages? Sorry for assuming your Asian heritage, the South Korean flag is on your Github account

**Comment by the-ethan-hunt** [comment]
A short search for NLP Chinese section landed me in these places:
- A CNN for chinese text classifications in TensorFlow
- Using deep learning for Chinese information extraction
- Recognizers by Microsoft for Chinese( currently developing Korean and Japanese)

For Korean:
- A R package for Korean NLP; koNLP(unmentioned in this awesome list; koNLPy is mentioned already)
- A whole new list of corpora, communities and POS taggers

Didn't have time for Japanese, though: sweat_smile: 
@NirantK , do you want me to begin for Korean? If so, then can you explain the initial steps?

**Comment by NirantK** [comment]
Thanks!

You can start either by adding a Non English Subheading in Libraries and
then for each language.

We might change that to keep the list as flat as possible with time.

Feel free to start with either Chinese or Korean. Please do remember to
remove/move content already in Python/R lists to avoid duplicates.

Thanks again! 👍

**Comment by NirantK** [comment]
@the-ethan-hunt thanks for creating the Korean section for us. Would you like to go ahead and create more for Chinese?

**Comment by the-ethan-hunt** [comment]
@NirantK  I searched for Chinese but found very very few. Almost all the libraries have been mentioned in the list previously and not much has changed since I posted this comment:
- A CNN for chinese text classifications in TensorFlow
- Using deep learning for Chinese information extraction
- Recognizers by Microsoft for Chinese( currently developing Korean and Japanese)

Do you want me to get going with it? IMHO, I don't think we need a PR for that.

**Comment by NirantK** [comment]
Thanks for the update @the-ethan-hunt 

Our present coverage of Chinese-NLP tools is not exhaustive, we need to improve that soon. I'll look into it. 

Consider Japanese or frankly, any other open issue? 

I'd be grateful for any help on #96 if you are looking at open issues. If nothing else, remove content that doesn't make sense and re-format the rest as per `awesome-lint` expectations.

**Comment by the-ethan-hunt** [comment]
Following this up from the issue #96 , I have found a list of NLP resources for:
- Arabic
- Chinese
- Spanish(This list is mentioned in the original awesome list)

Should I add each of them in individual PRs?

Secondly just a question: I now do have a certain amount of contribution too. (See @keon 's comment at #80 ). Does this make me eligible for a collaborator? :sweat_smile:

**Comment by NirantK** [comment]
I'd suggest a single PR with additions for all languages. You can keep 3 different commits and I'll not squash them so that it's easy to revisit when the changes were made. 

I'll defer that to @keon, I am still new and frequently wait to hear from him/her on major changes like this: https://github.com/keon/awesome-nlp/pull/110 where I've revamped the Python section heavily

**Comment by NirantK** [comment]
Just logging some major progress by @the-ethan-hunt in https://github.com/keon/awesome-nlp/pull/111 where he added Chinese, Arabic and Spanish tools and corpora. 

TODO: 
- Spanish Tools, preferably Python/PyTorch/TF
- More Japanese tools and corpora

**Comment by NirantK** [comment]
Merging this #113 to streamline contributor attention
